spring.application.name=inventory-management
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=achu
spring.datasource.password=achu123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true