spring.application.name=inventory-management
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB:PASSWORD:default_password}
//forpassword
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true